### ISSUE TITLE
Release On F-Droid & Google Play

### ISSUE THREAD

**Issue by OMGSoundboard** [OMGSoundboard/android-app#6]
**F-Droid**
- [X] [F-Droid RFP (Request for Packaging)](https://gitlab.com/fdroid/rfp/-/issues/2452)
- [x] [OMGSoundboard on F-Droid](https://f-droid.org/packages/audio.omgsoundboard/)

**Google Play**
- [x] [OMGSoundboard sent for review to Google Play](https://play.google.com/about/developer-content-policy/)
- [x] [OMGSoundboard available on Google Play](https://play.google.com/store/apps/details?id=audio.omgsoundboard)

**Comment by OMGSoundboard** [comment]
OMGSoundboard is now available on Google Play and F-Droid. ♥️

**Comment by OMGSoundboard** [comment]
Are you interested to include this app in your repo too, @IzzySoft?

**Comment by IzzySoft** [comment]
You want it restored there? Metadata have just been archived, so that's done easily. Checking the APK, there's one thing you could please take care for with future releases:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Easily solvved by a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Further, it would be good if you'd also include the `gradle-wrapper.jar` next to your `gradle-wrapper.properties`, for [Reproducible Builds](https://reproducible-builds.org/) :wink: 

That said: app is RB of course, just had to add the gradle-bin to the recipe manually for this release. And I see you'll switch it with the next (from 8.0 to 8.7). So to avoid having such things break RB, the JAR would be nice.

Welcome back then – I see the badge is already there :smiley:

**Comment by OMGSoundboard** [comment]
Thanks, @IzzySoft, you rock! 🤘
@Rashxz, may you please take care of the minor addition to the `build.gradle` and the `gradle-wrapper.jar`?

**Comment by IzzySoft** [comment]
Just a short heads-up: a new release showed up, but the JAR is still missing. This will delay updates for the RB shield each time, and requires manual actions for RB here. So it would be nice if you could add the wrapper JAR before the next release. Thanks in advance!

PS: after manual adjustments here, I can tell you that v12.0 succeeded as RB, though :wink:

**Comment by OMGSoundboard** [comment]
> Just a short heads-up: a new release showed up, but the JAR is still missing. This will delay updates for the RB shield each time, and requires manual actions for RB here. So it would be nice if you could add the wrapper JAR before the next release. Thanks in advance!
> 
> PS: after manual adjustments here, I can tell you that v12.0 succeeded as RB, though 😉

The wrapper is now included and we have a `foss` flavor without the [Wear OS by Google](https://wearos.google.com/i) stuff that is proprietary unfortunately, @IzzySoft.

**Comment by IzzySoft** [comment]
> The wrapper is now included

Haha… good, and we meanwhile have our own for such cases now :see_no_evil:

> we have a foss flavor without the [Wear OS by Google](https://wearos.google.com/i) stuff that is proprietary unfortunately,

Yeah, unfortunately that is the case for Wear (and many of the apps which formerly shipped with AOSP). You want us to switch to the FOSS flavor then? Does it have its own package name so it can be established next to the other?

**Comment by OMGSoundboard** [comment]
> > The wrapper is now included
> 
> Haha… good, and we meanwhile have our own for such cases now 🙈
> 
> > we have a foss flavor without the [Wear OS by Google](https://wearos.google.com/i) stuff that is proprietary unfortunately,
> 
> Yeah, unfortunately that is the case for Wear (and many of the apps which formerly shipped with AOSP). You want us to switch to the FOSS flavor then? Does it have its own package name so it can be established next to the other?

It's the same package name.
If you're fine with Wear OS you may keep that version.

**Comment by IzzySoft** [comment]
Well, *I* don't even use Wear (for this very reason). Do you feel it an essential part of the app – or rather a nice-to-have addon? Maybe it could even literally be made an addon to be loaded separately (using a "shared key" if needed to access the data)?

**Comment by IzzySoft** [comment]
Btw, the FOSS flavor still contains GMS.

**Comment by OMGSoundboard** [comment]
> Well, _I_ don't even use Wear (for this very reason). Do you feel it an essential part of the app – or rather a nice-to-have addon? Maybe it could even literally be made an addon to be loaded separately (using a "shared key" if needed to access the data)?

It is a nice addon. I don't have a smartwatch too.

> Btw, the FOSS flavor still contains GMS.

Thanks for the hint, @IzzySoft. Today's release should be `floss` hopefully.

**Comment by IzzySoft** [comment]
I didn't want to wait (but have the AF gone with the next sync), so I've manually triggered its update – and can confirm: GMS is gone, AF will now be removed :partying_face:

Only thing the scanner yielded was:

    ! repo/audio.omgsoundboard_17.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE*

The asterisk indicates it was granted implicitly, most likely because of WRITE being requested… Yupp:

```
Permissions:
------------
* android.permission.INTERNET
* android.permission.ACCESS_NETWORK_STATE
* android.permission.WRITE_SETTINGS
* android.permission.WRITE_EXTERNAL_STORAGE
* audio.omgsoundboard.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
* android.permission.READ_EXTERNAL_STORAGE*
```

I guess the soundboards will be saved outside the app's scope? And I wonder:

> _OMGSoundboard_ works offline

Hm, strange offline permissions – and the app description gives no clue. Something the cat dragged in (aka "dependency hell") – or something intended that's just missing from the app description?
